services:
  shlink:
    image: shlinkio/shlink:stable
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - db

    environment:
      - TZ=${TZ}
      - DEFAULT_DOMAIN=${SHLINK_DOMAIN}
      - IS_HTTPS_ENABLED=true

      - DB_DRIVER=maria
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    networks:
      - backbone

  db:
    image: mariadb:11
    container_name: ${CONTAINER_NAME}-db
    restart: unless-stopped

    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

    volumes:
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/data:/var/lib/mysql

    networks:
      - backbone

networks:
  backbone:
    name: ${HOMELAB_BACKBONE_NETWORK}
    external: true
