services:
  shlink:
    image: shlinkio/shlink:stable
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    environment:
      - TZ=${TZ}
      - DEFAULT_DOMAIN=${SHLINK_DOMAIN}
      - IS_HTTPS_ENABLED=true

      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    networks:
      - backbone

networks:
  backbone:
    name: ${HOMELAB_BACKBONE_NETWORK}
    external: true
