services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    environment:
      - TZ=${TZ}

    networks:
      - backbone

networks:
  backbone:
    name: ${HOMELAB_BACKBONE_NETWORK}
    external: true
