apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-linkding
  namespace: linkding
spec:
  instances: 1
  storage:
    size: 2Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
