# [env]
# ENVIRONMENT = "homelab"
# DOCKER_CONTEXT = "homelab"

[tools]
docker-cli = "latest"
docker-compose = "latest"
kubectl = "latest"
k9s = "latest"
helm = "latest"
kubectx = "latest"
stern = "latest"
flux2 = "latest"
talosctl = "latest"

[env]
KUBECONFIG = "{{config_root}}/k8s/kubeconfig.yaml"
