---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Services"
subtitle: "Dashboard"
#logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false 
columns: "4"

# Optional theme customization
stylesheet:
   - 'assets/catppuccin-latte.css'

# Optional message
#message:
#  #url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/cmpi66"
    target: "_blank" # optional html a tag target attribute
  # - name: "Wiki"
  #   icon: "fas fa-book"
  #   url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "Blog"
    icon: "fas fa-file-alt"
    url: "https://notes.munozpi.com" 
    target: "_blank" # optional html a tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Management"
    icon: "fas fa-cloud"
    items:
      - name: "pfsense"
        logo: "assets/pfsense.png"
        subtitle: "pfsense box"
        tag: "app"
        url: "https://pfsense.cmlabs.xyz"
        target: "_blank" # optional html a tag target attribute
      - name: "pihole"
        logo: "assets/pihole.png"
        subtitle: "pihole dns"
        tag: "app"
        url: "https://pihole.cmlabs.xyz"
        target: "_blank" # optional html a tag target attribute
      - name: "Truenas"
        logo: "assets/truenas.png"
        subtitle: "NAS"
        tag: "app"
        url: "https://truenas.cmlabs.xyz"
        target: "_blank" # optional html a tag target attribute
      - name: "dockhand"
        logo: "assets/dockhand.png"
        subtitle: "dockhand on xps"
        tag: "app"
        url: "https://dockhand.cmlabs.xyz"
        target: "_blank" # optional html a tag target attribute
      - name: "dozzle"
        logo: "assets/dozzle.png"
        subtitle: "dockhand on xps"
        tag: "app"
        url: "https://dozzle.cmlabs.xyz"
        target: "_blank" # optional html a tag target attribute
      - name: "Adminer"
        logo: "assets/adminer.png"
        subtitle: "Adminer on xps"
        tag: "app"
        url: "https://adminer.cmlabs.xyz"
        target: "_blank" # optional html a tag target attribute
      - name: "Authentik"
        logo: "assets/authentik.png"
        subtitle: "Authentik on xps"
        tag: "app"
        url: "https://authentik.cmlabs.xyz"
        target: "_blank" # optional html a tag target attribute
  - name: "Tools"
    icon: "fas fa-cloud"
    items:
      - name: "Netdata"
        logo: "assets/tools/sample.png"
        subtitle: "Lights Out Monitoring"
        tag: "app"
        url: "https://10.10.30.13/login.html/"
        target: "_blank" # optional html a tag target attribute
      - name: "Daffy - iLO"
        logo: "assets/tools/sample.png"
        subtitle: "Lights Out Monitoring"
        tag: "app"
        url: "https://10.10.0.102/"
      - name: "Scrutiny"
        logo: "assets/tools/sample.png"
        subtitle: "SMART data at a glance"
        tag: "app"
        url: "https://10.10.0.102/"
  - name: "External"
    icon: "fas fa-cloud"
    items:
      - name: "Plex"
        logo: "assets/tools/sample.png"
        subtitle: "Plex Media Server"
        tag: "app"
        url: "https://10.10.2.101:32400"
        target: "_blank" # optional html a tag target attribute
      - name: "Tautulli"
        logo: "assets/tools/sample.png"
        subtitle: "Plex Monitoring and Management"
        tag: "app"
        url: "https://10.10.2.101:8181"
      - name: "Scrutiny"
        logo: "assets/tools/sample.png"
        subtitle: "SMART Info at a Glance"
        tag: "app"
        url: "10.10.2.101:8080/web/dashboard"
      - name: "Portainer - svr-plex-01"
        logo: "assets/tools/sample.png"
        subtitle: "Portainer instance residing on svr-plex-01"
        tag: "app"
        url: "http://10.10.2.101:9000/#!/home"
