services:
  databasus:
    container_name: ${CONTAINER_NAME}
    image: databasus/databasus:latest
    volumes:
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/data:/databasus-data
    restart: unless-stopped

    networks:
      - backbone

networks:
  backbone:
    name: ${HOMELAB_BACKBONE_NETWORK}
    external: true
