services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/data:/app/data

    networks:
      - backbone

networks:
  backbone:
    external: true
    name: ${HOMELAB_BACKBONE_NETWORK}
