networks:
  backbone:
    name: ${HOMELAB_BACKBONE_NETWORK}
    external: true

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:14
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - db

    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=${DB_NAME}
      - FORGEJO__database__USER=${DB_USER}
      - FORGEJO__database__PASSWD=${DB_PASSWORD}

    volumes:
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/data:/data
      - /etc/localtime:/etc/localtime:ro

    networks:
      - backbone

    ports:
      - "2222:22"

  db:
    image: postgres:14
    container_name: ${CONTAINER_NAME}-db
    restart: unless-stopped

    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    networks:
      - backbone

    volumes:
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/postgres:/var/lib/postgresql/data
