services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:1.21
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    environment:
      - USER_UID=1000
      - USER_GID=1000

      - FORGEJO__database__DB_TYPE=mysql
      - FORGEJO__database__HOST=${DB_HOST}:3306
      - FORGEJO__database__NAME=${DB_NAME}
      - FORGEJO__database__USER=${DB_USER}
      - FORGEJO__database__PASSWD=${DB_PASSWORD}

      - FORGEJO__server__DOMAIN=${FORGEJO_DOMAIN}
      - FORGEJO__server__ROOT_URL=https://${FORGEJO_DOMAIN}
      - FORGEJO__server__SSH_DOMAIN=${FORGEJO_SSH_DOMAIN}
      - FORGEJO__server__SSH_PORT=${FORGEJO_SSH_PORT}

      - TZ=${TZ}

    volumes:
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/data:/data

    networks:
      - backbone

    ports:
      - "2222:22"
networks:
  backbone:
    name: ${HOMELAB_BACKBONE_NETWORK}
    external: true
