services:
  caddy:
    image: caddy:2
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    ports:
      - "${CADDY_HTTP_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"

    environment:
      TZ: ${TZ}

    volumes:
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/init:/etc/caddy:ro
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/data:/data
      - ${HOMELAB_DATA_ROOT}/${SERVICE_DATA_SUBDIR}/config:/config

    networks:
      - backbone

networks:
  backbone:
    external: true
    name: ${HOMELAB_BACKBONE_NETWORK}
